In [1]:
import pandas as pd

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [2]:
data = pd.read_csv(r'C:\Users\clozy\opencv\Scripts\jpnb\CREATING\Regression\3.0\diamonds_processed.csv')

data.head()

,Unnamed: 0,clarity,price,cut_Fair,cut_Good,cut_Ideal,cut_Premium,cut_Very Good,color_D,color_E,...,color_G,color_H,color_I,color_J,carat,depth,table,x,y,z
0,0,3,1436,0,0,0,0,1,0,0,...,0,0,0,0,-0.640724,0.804026,-0.209734,-0.611707,-0.572127,-0.497418
1,1,5,2340,0,0,1,0,0,0,0,...,0,0,1,0,-0.174970,0.457059,-1.977360,0.004280,0.030098,0.078585
2,2,6,607,0,0,0,0,1,0,0,...,1,0,0,0,-1.085308,-0.236875,-0.651640,-1.334823,-1.318168,-1.332622
3,3,1,2464,0,0,1,0,0,0,1,...,0,0,0,0,-0.132629,0.110092,-0.651640,0.048917,0.075040,0.078585
4,4,3,544,0,0,1,0,0,0,0,...,1,0,0,0,-1.042967,0.457059,-1.535454,-1.236622,-1.219295,-1.174221

In [3]:
data.drop(['Unnamed: 0'], axis=1, inplace=True)

In [4]:
data.head()

,clarity,price,cut_Fair,cut_Good,cut_Ideal,cut_Premium,cut_Very Good,color_D,color_E,color_F,color_G,color_H,color_I,color_J,carat,depth,table,x,y,z
0,3,1436,0,0,0,0,1,0,0,1,0,0,0,0,-0.640724,0.804026,-0.209734,-0.611707,-0.572127,-0.497418
1,5,2340,0,0,1,0,0,0,0,0,0,0,1,0,-0.174970,0.457059,-1.977360,0.004280,0.030098,0.078585
2,6,607,0,0,0,0,1,0,0,0,1,0,0,0,-1.085308,-0.236875,-0.651640,-1.334823,-1.318168,-1.332622
3,1,2464,0,0,1,0,0,0,1,0,0,0,0,0,-0.132629,0.110092,-0.651640,0.048917,0.075040,0.078585
4,3,544,0,0,1,0,0,0,0,0,1,0,0,0,-1.042967,0.457059,-1.535454,-1.236622,-1.219295,-1.174221

In [5]:
from sklearn.linear_model import LinearRegression

def linear_model(x_train, y_train):
    
    print('Linear Regression')
    linear_regression = LinearRegression()
    
    linear_regression.fit(x_train, y_train)
    
    return linear_regression

In [6]:
from sklearn.linear_model import Lasso

def lasso_model(x_train, y_train):
    
    print('Lasso Regression')
    #aplha determines strength of regularization
    lasso_regression = Lasso(alpha=0.8, max_iter=10000)
    
    lasso_regression.fit(x_train, y_train)
    
    return lasso_regression

In [7]:
 from sklearn.linear_model import Ridge

def ridge_model(x_train, y_train):
    
    print('Ridge Regression')
    ridge_regression = Ridge(alpha=0.9)
    
    ridge_regression.fit(x_train, y_train)
    
    return ridge_regression

In [11]:
def build_and_train_model(data, target_name, reg_fn):
    
    X = data.drop(target_name, axis=1)
    Y = data[target_name]
    
    x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)
    
    model = reg_fn(x_train, y_train)
    
    score = model.score(x_train, y_train)
    print('training score : ', score)
    
    y_pred = model.predict(x_test)
    r_score = r2_score(y_test, y_pred)
    print('Testing score : ', r_score )
    
    return {'model' : model,
           'x_train' : x_train, 'x_test' : x_test,
           'y_train' : y_train, 'y_test' : y_test,
           'y_pred' : y_pred}

In [12]:
linear_reg = build_and_train_model(data, 'price', linear_model)

Linear Regression
training score :  0.9117604354082759
Testing score :  0.9010965164321642

In [13]:
ridge_reg = build_and_train_model(data, 'price', ridge_model)

Ridge Regression
training score :  0.9117589690967237
Testing score :  0.9012289860881795

In [14]:
lasso_reg = build_and_train_model(data, 'price', lasso_model)

Lasso Regression
training score :  0.9116935024706889
Testing score :  0.9012605234632959

In [15]:
linear_reg['model']

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [16]:
from sklearn.linear_model import SGDRegressor

def sgd_model(x_train, y_train):
    
    print('SGD Regressor')
    sgd_regressor = SGDRegressor(max_iter=2000)
    
    sgd_regressor.fit(x_train, y_train)
    
    return sgd_regressor

In [17]:
sgd_reg = build_and_train_model(data, 'price', sgd_model)

SGD Regressor
training score :  0.9112392000331259
Testing score :  0.9006634095177732